import { AfterViewInit, Component, ViewChild, OnInit } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { SendingService } from '../../services/sending.service';
import { Message } from '../../../../models/common/message';

@Component({
  selector: 'app-sending-list',
  templateUrl: './sending-list.component.html',
  styleUrls: ['./sending-list.component.css'],
})
export class SendingListComponent implements OnInit, AfterViewInit {
  public displayedColumns: any[];
  public messages!: Message[];
  public dataSource!: MatTableDataSource<Message>;
  @ViewChild(MatPaginator) paginator!: MatPaginator;

  constructor(
    private _sendingService: SendingService,
  ) {
    this.displayedColumns = [
      'id',
      'message',
      'destinations',
    ];
    this.messages = [
      {messageId: 1,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 2,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 3,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 4,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 5,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 6,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 7,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 8,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 9,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 10,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 11,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 12,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 13,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 14,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 15,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 16,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 17,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 18,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 19,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
      {messageId: 20,message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi enim aperiam deserunt architecto! Earum aperiam dolorem voluptates nemo, delectus tenetur debitis voluptate quod deleniti, quibusdam neque, vel possimus ex enim!", destinations: '99999999, 88888888'},
  
    ];
    this.dataSource = new MatTableDataSource(this.messages);
  }

  ngOnInit(): void {
    this._sendingService.requestGetAll().subscribe({
      next: (res) => {
        console.log(res);
        // this.messages = res.data;   
      }
    });
  }

  ngAfterViewInit(): void {
    this.dataSource.paginator = this.paginator;
  }

}